twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null

    form_themes: ['bootstrap_5_layout.html.twig']

    paths:
        "%kernel.project_dir%/public": public_path
        '%kernel.project_dir%/templates/_components': components
        '%kernel.project_dir%/templates/layouts': layouts
        '%kernel.project_dir%/templates/_partials': partials
        '%kernel.project_dir%/templates/pages': pages
        '%kernel.project_dir%/templates/emails': emails

